### ISSUE TITLE
Unable to load firmware from SD card, not showing up?

### ISSUE THREAD

**Issue by gazzer82** [nerves-project/nerves_system_grisp2#48]
### Environment

* Elixir version (`elixir -v`): Erlang/OTP 25 [erts-13.1.5] [source] [64-bit] [smp:10:10] 

```
[ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.14.3 (compiled with Erlang/OTP 25)
```

* Nerves environment: (`mix nerves.env --info`)
==> nerves
==> up_tally_firmware
```
|nerves_bootstrap| Environment Package List

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.9.3
  Type:        toolchain_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_toolchain_armv7_nerves_linux_gnueabihf
  Vsn:         1.8.0
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_system_br
  Vsn:         1.22.5
  Type:        system_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_system_grisp2
  Vsn:         0.6.2
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Docker, [make_args: ["source", "all", "legal-info"]]}

|nerves_bootstrap| Loadpaths Start

|nerves_bootstrap| Precompile Start

==> nerves_toolchain_armv7_nerves_linux_gnueabihf
|nerves_bootstrap| Compile.NervesPackage start

|nerves_bootstrap| Compile.NervesPackage end

==> nerves_system_grisp2
|nerves_bootstrap| Compile.NervesPackage start

|nerves_bootstrap| Compile.NervesPackage end

==> up_tally_firmware
|nerves_bootstrap| Precompile End


Nerves environment
  MIX_TARGET:   grisp2
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     grisp2
  toolchain:  /Users/garethjeanne/.nerves/artifacts/nerves_toolchain_armv7_nerves_linux_gnueabihf-darwin_arm-1.8.0
  system:     /Users/garethjeanne/.nerves/artifacts/nerves_system_grisp2-portable-0.6.2
  app:        .

|nerves_bootstrap| Loadpaths End
```

* Additional information about your host, target hardware or environment that
  may help

Developing on an M1X MacBook Pro

### Current behavior

I am trying to flash the built image onto the Grisp2 board as per the instructions, SD card is formatted as MBR/Fat32, but nothing is showing up on the Grip2 under /mnt/mmc just and empty folder.

Any ideas what could be causing the issues, it's a Sandisk Ultra, 32GB UHS-I microSDHC Card.

### Expected behavior

To be able to the firmware file I have uploaded to the SD card.

**Comment by fhunleth** [comment]
Do you have a second MicroSD card to try? Perhaps a smaller one? It seems like you should at least be able to see the file. I don't remember there being a limitation on MicroSD card types with GRiSP, but sometimes on other devices the big ones don't work.

**Comment by gazzer82** [comment]
So tried this again today, and it worked fine. Apologies I have no idea why it's suddenly working now and it wasn't before, can only assume operator error somewhere!
